name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 1.0.0)'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write  # For trusted publishing to PyPI
      contents: read   # For checking out the code
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install Poetry
        uses: snok/install-poetry@v1.4.1
        with:
          version: latest
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: poetry install --no-interaction --no-root

      - name: Install project
        run: poetry install --no-interaction

      - name: Update version from tag or input
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            # Extract version from git tag (remove 'v' prefix if present)
            VERSION=${GITHUB_REF#refs/tags/}
            VERSION=${VERSION#v}
            echo "Release triggered: Setting version to $VERSION"
          else
            # Manual workflow dispatch
            VERSION="${{ github.event.inputs.version }}"
            echo "Manual trigger: Setting version to $VERSION"
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          poetry version $VERSION

      - name: Build package
        run: poetry build

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true


